[pytest]
pythonpath = .
testpaths = tests
bdd_features_base_dir = tests/acceptance/features/
markers =
    node(name): mark acceptance scenario with node id tag
    node.shape.intake: acceptance scenario tagged for shape.intake node
